[project]
name = "g-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=25.11.0",
    "fastapi>=0.125.0",
    "isort>=7.0.0",
    "langchain>=1.1.0",
    "langchain-community>=0.4.1",
    "langchain-core>=1.1.0",
    "langchain-ollama>=1.0.0",
    "langchain-pinecone>=0.2.13",
    "langchain-tavily>=0.2.16",
    "langchainhub>=0.1.21",
    "pypdf>=6.4.2",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
